Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Interpretador e Editor de Algoritmos
// Autor(a)    : Luana Kulczynski Oliveira
// Data atual  : 23/11/2020
Var
// Seção de Declarações das variáveis
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("Resultado:", nota)

Fimalgoritmo